# Generated by Django 4.0.6 on 2022-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_database', '0002_alter_contact_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(choices=[('FIT', 'Quiero mejorar mi condición física'), ('SPO', 'Soy deportista y quiero mejorar mi rendimiento'), ('PAI', 'Sufro de dolor o lesiones'), ('OTH', 'Otro')], max_length=3, verbose_name='Motivo principal de la Consulta'),
        ),
    ]
