# Generated by Django 4.0.6 on 2022-07-31 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_database', '0003_alter_contact_message_alter_contact_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
    ]
